CHORE: Support multiple node versions
aligent/serverless-docker pull request #193
Opened 2023-05-01 05:28 UTC by AdamJHall

This PR adds in a build hook script to build multiple "flavours"  of this docker image so we can support different versions of node with the same docker files.

This will require updating our build triggers as well, we would need: 
![image](https://user-images.githubusercontent.com/7251527/235410981-f3cf7660-5123-46d2-bfac-19f08548d10f.png)

I have discussed with @tvhees and we think there should also be an updated bash alias script to auto-switch between the the node 18 image and node 16 image based on the `.nvmrc` file in the project. I'll add a separate PR for that later.

2023-05-01 05:29 UTC, AdamJHall commented
Also just an question to all, do we still need the `-offline` image?

2023-05-02 00:25 UTC, TheOrangePuff commented
> Also just an question to all, do we still need the `-offline` image?

I was thinking about this the other day... I don't think we use it?

2023-05-02 00:28 UTC, tvhees commented
> > Also just an question to all, do we still need the `-offline` image?
> 
> I was thinking about this the other day... I don't think we use it?

Not to my knowledge.

2023-05-02 02:26 UTC, tvhees reviewed
This looks like it removes version the version number from the linux image as well e.g. it will build `FROM node:16-alpine` instead of `FROM node:16.11-alpine3.14`

Just checking that's intended?

2023-05-02 02:26 UTC, AdamJHall commented
@TheOrangePuff and @tvhees,

Ok, I've remove the offline image then as well as it simplifies the build hook and rules a bit.

2023-05-02 02:28 UTC, AdamJHall commented
> This looks like it removes version the version number from the linux image as well e.g. it will build `FROM node:16-alpine` instead of `FROM node:16.11-alpine3.14`
> 
> Just checking that's intended?

Yes, sorry I should have mentioned that. I removed it as there is no alpine3.14 for node 18 and it doesn't look like it's necessary AFAICT, both images build fine without it.

2023-05-03 03:37 UTC, TheOrangePuff requested changes

2023-05-03 03:47 UTC, AdamJHall commented on hooks/build
> +    NODE_TAG="16-alpine"
Can do! Pushed up a new change to just pull it out of the tag and use it now.

2023-05-04 04:43 UTC, TheOrangePuff approved these changes

2023-05-04 04:51 UTC, merged